<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('user', 'email', 'string', '255', array(
             'unique' => '1',
             ));
    }

    public function down()
    {

    }
}